### ISSUE TITLE
Loggers should filter information from exceptions

### ISSUE THREAD

**Issue by amyspark** [piotrmurach/tty-logger#8]
### Are you in the right place?
* For issues or feature requests file a GitHub issue in this repository
* For general questions or discussion post in [Gitter](https://gitter.im/piotrmurach/tty)

### Describe the problem

Loggers should be able to filter information from exceptions.

### Steps to reproduce the problem

```ruby
#!/usr/bin/env ruby
# frozen_string_literal: true

require 'tty-command'
require 'tty-logger'
require 'tty-option'

# rubocop disable Style/Documentation
class Demo
  include TTY::Option

  argument :arg1 do
    required
  end

  def initialize
    @logger = TTY::Logger.new do |config|
      config.metadata = %i[date time]
      config.filters.data = %i[arg1]
      config.level = :debug
    end
    @cmd = TTY::Command.new(printer: :null)
  end

  def protect_params
    @logger = @logger.copy Hash.new do |config|
      config.filters.message = [params[:arg1]]
    end
  end

  def demo
    @logger.info "running demo"

    @cmd.run "cat /etc/hosts; echo #{params[:arg1]}; false"
  end

  def run!
    parse
    protect_params
    demo
  rescue StandardError => e
    @logger.fatal 'Error:', e
  end
end

Demo.new.run!
```

### Actual behaviour

```
❯ bundle exec ruby _scripts/demo-2.rb localhost
[2020-04-27] [13:49:06.820] › ℹ info    running demo             
Traceback (most recent call last):
        3: from _scripts/demo-2.rb:46:in `<main>'
        2: from _scripts/demo-2.rb:40:in `run!'
        1: from _scripts/demo-2.rb:34:in `demo'
/home/amalia/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/tty-command-0.9.0/lib/tty/command.rb:106:in `run': Running `cat /etc/hosts; echo localhost; false` failed with (TTY::Command::ExitError)
  exit status: 1
  stdout: #<ip-address> <hostname.domain.org>   <hostname>
127.0.0.1       localhost.localdomain   localhost       Home
::1     localhost.localdomain   localhost       Home
localhost
  stderr: Nothing written
        12: from _scripts/demo-2.rb:46:in `<main>'
        11: from _scripts/demo-2.rb:37:in `run!'
        10: from _scripts/demo-2.rb:42:in `rescue in run!'
         9: from /home/amalia/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/tty-logger-0.3.0/lib/tty/logger.rb:45:in `fatal'
         8: from /home/amalia/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/tty-logger-0.3.0/lib/tty/logger.rb:237:in `log'
         7: from /home/amalia/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/tty-logger-0.3.0/lib/tty/logger.rb:276:in `filter'
         6: from /home/amalia/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/tty-logger-0.3.0/lib/tty/logger.rb:276:in `reduce'
         5: from /home/amalia/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/tty-logger-0.3.0/lib/tty/logger.rb:276:in `each'
         4: from /home/amalia/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/tty-logger-0.3.0/lib/tty/logger.rb:277:in `block in filter'
         3: from /home/amalia/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/tty-logger-0.3.0/lib/tty/logger.rb:277:in `tap'
         2: from /home/amalia/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/tty-logger-0.3.0/lib/tty/logger.rb:278:in `block (2 levels) in filter'
         1: from /home/amalia/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/tty-logger-0.3.0/lib/tty/logger.rb:278:in `each'
/home/amalia/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/tty-logger-0.3.0/lib/tty/logger.rb:279:in `block (3 levels) in filter': undefined method `gsub!' for #<TTY::Command::ExitError:0x00005581411b8218> (NoMethodError)
```

### Expected behaviour

It should not print `localhost` on either the command line or the output itself.

### Describe your environment

* OS version: `5.4.34-1-MANJARO`
* Ruby version: `ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]`
* TTY version:  `tty-command (0.9.0)`, `tty-logger (0.3.0)`

**Comment by amyspark** [comment]
This line: https://github.com/piotrmurach/tty-logger/blob/edebbb3bb93713dc3c9f5a126e5e5174779e6cc7/lib/tty/logger.rb#L277
assumes every message is a String, which is not correct
https://github.com/piotrmurach/tty-logger/blob/edebbb3bb93713dc3c9f5a126e5e5174779e6cc7/lib/tty/logger/event.rb#L28-L37
on these cases.

**Comment by piotrmurach** [comment]
Thank you for this great report. Now the sensitive info is correctly filtered:

```
[2020-07-29] [21:08:24.553] › ! fatal   Error: Running `cat /etc/hosts; echo [FILTERED]; false` failed with
  exit status: 1
  stdout: ##
# Host Database
#
# [FILTERED] is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	[FILTERED]
255.255.255.255	broadcasthost
::1             [FILTERED] 
[FILTERED]
  stderr: Nothing written
```
